# Generated by Django 5.2.11 on 2026-02-26 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='upload/videos/')),
                ('original_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-upload_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(db_index=True, max_length=20)),
                ('confidence', models.FloatField()),
                ('frame_number', models.IntegerField()),
                ('bbox_x', models.IntegerField(blank=True, null=True)),
                ('bbox_y', models.IntegerField(blank=True, null=True)),
                ('bbox_w', models.IntegerField(blank=True, null=True)),
                ('bbox_h', models.IntegerField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_plates', to='detection.videoupload')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
